---
schemaVersion: 2.2.0
metadata:
  name: ansible-role-molecule-test
  displayName: Ansible Role Molecule Test
  description: Ansible Role for testing with Molecule
  version: 0.0.0
  projectType: ansible
  language: yaml
  tags:
    - ansible
    - molecule
  icon: https://raw.githubusercontent.com/devicons/devicon/master/icons/ansible/ansible-original.svg
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
projects:
  - name: ansible-role-molecule-test
    git:
      remotes:
        origin: https://github.com/ucomesdag/ansible-role-molecule-test.git
components:
  - name: dev-tools
    container:
      image: quay.io/ucomesdag/developer-tools:latest
      memoryLimit: 2Gi
      memoryRequest: 256Mi
commands:
  - id: lint
    exec:
      commandLine: molecule lint
      component: dev-tools
      workingDir: /projects/ansible-role-test
      label: Molecule Lint
  - id: test
    exec:
      commandLine: molecule test
      component: dev-tools
      workingDir: /projects/ansible-role-test
      label: Molecule Test
  - id: yamllint
    exec:
      commandLine: yamllint .
      component: dev-tools
      workingDir: /projects/ansible-role-test
      label: Yamllint
  - id: ansible-navigator
    exec:
      commandLine: ansible-navigator
      component: dev-tools
      workingDir: /projects/ansible-role-test
      label: Ansible Navigator
  - id: ansible-playbook
    exec:
      commandLine: ansible-playbook
      component: dev-tools
      workingDir: /projects/ansible-role-test
      label: Ansible Playbook
