---
# tasks file for molecule_test

- name: Gather OS info
  ansible.builtin.setup:
    filter: ansible_os_family

- name: Include vars based on OS family {{ ansible_facts['os_family'] }}
  ansible.builtin.include_vars:
    file: "{{ ansible_facts['os_family'] }}.yml"

- name: Install package {{ molecule_test_httpd_package }}
  ansible.builtin.package:
    name: "{{ molecule_test_httpd_package }}"
    state: present
  notify: restart_webserver

- name: Copy content
  ansible.builtin.copy:
    content: "{{ molecule_test_webpage_content }}"
    dest: "{{ molecule_test_httpd_dir }}/index.html"
    mode: "0644"
  notify: restart_webserver
